name: "Secret Scanner"
description: "Scans for secrets using Talisman"
inputs:
  fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    required: false
    default: "0"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Install Talisman
      shell: bash
      run: |
        curl --silent -o talisman https://github.com/thoughtworks/talisman/releases/latest/download/talisman_linux_amd64
        chmod +x talisman
        sudo mv talisman /usr/local/bin/

    - name: Run Talisman
      shell: bash
      run: talisman --scan
