name: "Secret Scanner"
description: "Scans for secrets using Gitleaks"
inputs:
  fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    required: false
    default: "0"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
